-- 코드를 작성해주세요
SELECT dp.ID, dp.EMAIL, dp.FIRST_NAME, dp.LAST_NAME
FROM DEVELOPERS dp
WHERE (dp.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0 
OR (dp.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0
ORDER BY dp.ID